services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - ./odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    # Fixes common fresh-volume crash: missing /var/lib/odoo/addons/17.0
    command: bash -lc "mkdir -p /var/lib/odoo/addons/17.0 /var/lib/odoo/.local/share/Odoo/addons/17.0 && odoo -c /etc/odoo/odoo.conf"
